name: Build Windows

permissions:
  contents: write

on:
  push:
    branches:
      - '*'           # Runs on all branch pushes

jobs:
  cross-platform-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Python Script on Linux
        run: |
          cd tools/lookup_table/
          python3 generate_lookup_table.py --logging debug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lookup-output
          path: tools/lookup_table/output/lookuptable.json

  build-win:
    needs: cross-platform-task
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set version in src/renderer/src/assets/version.json
        id: set_version
        run: |
          # for getting the correct filename to rename
          $envversion = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
          echo "envversion=$envversion" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

          # for populating src/renderer/src/assets/version.json
          $version = "${{ github.run_number }}"
          $branch = "${{ github.ref_name }}"
          $commit_hash = "${{github.sha }}"

          $version_data = @{
            "version"     = $version
            "branch"      = $branch
            "commit hash" = $commit_hash
          }

          $version_data | ConvertTo-Json | set-content -Force -Path src/renderer/src/assets/version.json
          get-content src/renderer/src/assets/version.json

      - name: Remove lookup table from git repo
        id: del_char_lookup
        run: |
          rm tools\lookup_table\output\lookuptable.json

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: lookup-output
          path: tools\lookup_table\output\

      # - name: Debug lookup table from git repo
      #   id: debug_char_lookup
      #   run: |
      #     Get-ChildItem -Depth 2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'  # Adjust this to the required Node.js version
          cache: 'npm'

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Cache Electron
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/custom-electron-builder-cache
          key: ${{ runner.os }}-electron-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-electron-cache-

      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build for Windows
        run: npm run build:win

      - name: Get debug info
        run: |
          cat dist/latest.yml

      - name: Overrule stuffs
        run: |
        
          # exe name 
          $NewSetupName = "Admin-GooWee-Setup-${{ github.ref_name }}-${{ github.run_number }}.exe"
          echo "newsetupname=$NewSetupName" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
          Rename-Item -Path "dist/admin-goowee-finale-${{ env.envversion }}-setup.exe" -NewName "$NewSetupName"

          # latest.yml content

          # [0]version: 1.0.0
          # [1]files:
          # [2]  - url: admin-goowee-finale-1.0.0-setup.exe
          # [3]    sha512: NSo0bzE6FE9p8TOyeHn3OX8vIMZJqm+r68JqzjxqHGTfjSA8kDvE1xK5TS4nU1UoJW7EUYEBfidXRZcONtp3TA==
          # [4]    size: 94177366
          # [5]path: admin-goowee-finale-1.0.0-setup.exe
          # [6]sha512: NSo0bzE6FE9p8TOyeHn3OX8vIMZJqm+r68JqzjxqHGTfjSA8kDvE1xK5TS4nU1UoJW7EUYEBfidXRZcONtp3TA==
          # [7]releaseDate: '2024-11-25T20:49:34.125Z'

          $latest_content = get-content -Path dist/latest.yml
          $latest_content[0] = $latest_content[0] -replace "version: 1.0.0", "version: ${{ env.envversion }}"
          $latest_content[2] = $latest_content[2] -replace "  - url: admin-goowee-finale-1.0.0-setup.exe", "  - url: $NewSetupName"
          $latest_content[5] = $latest_content[5] -replace "path: admin-goowee-finale-1.0.0-setup.exe", "path: $NewSetupName"
          $latest_content | Set-Content -Path dist/latest.yml -force
          cat -Path dist/latest.yml

      # - name: Get debug info
      #   run: |
      #     ls env:
      #     ls
      #     cat latest.yml

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "build-windows-output"
          path: dist/${{ env.newsetupname }}
          retention-days: 7
