name: Build Windows

permissions:
  contents: write

on:
  push:
    branches:
      - '*'           # Runs on all branch pushes

jobs:
  cross-platform-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Python Script on Linux
        run: |
          cd tools/lookup_table/
          python3 generate_lookup_table.py --logging debug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lookup-output
          path: tools/lookup_table/output/lookuptable.json

  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set version in src/renderer/src/assets/version.json
        id: set_version
        run: |
          # for getting the correct filename to rename
          $envversion = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
          echo "envversion=$envversion" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

          # for populating src/renderer/src/assets/version.json
          $version = "${{ github.run_number }}"
          $branch = "${{ github.ref_name }}"
          $commit_hash = "${{github.sha }}"

          $version_data = @{
            "version"     = $version
            "branch"      = $branch
            "commit hash" = $commit_hash
          }

          $version_data | ConvertTo-Json | set-content -Force -Path src/renderer/src/assets/version.json
          get-content src/renderer/src/assets/version.json

      - name: Remove lookup table from git repo
        id: del_char_lookup
        run: |
          rm tools\lookup_table\output\lookuptable.json

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: lookup-output
          path: tools\lookup_table\output\

      - name: Debug lookup table from git repo
        id: debug_char_lookup
        run: |
          cat tools\lookup_table\output\lookuptable.json

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'  # Adjust this to the required Node.js version
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build for Windows
        run: npm run build:win

      - name: Get env
        run: |
          ls env:

      - name: Rename exe
        run: |
          $NewSetupName = "Admin-GooWee-Setup-${{ github.ref_name }}-${{ github.run_number }}.exe"
          echo "newsetupname=$NewSetupName" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
          Rename-Item -Path "dist/admin-goowee-finale-${{ env.envversion }}-setup.exe" -NewName "$NewSetupName"
      
      - name: Get env
        run: |
          ls env:

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "build-windows-output"
          path: dist/${{ env.newsetupname }}
          retention-days: 7
